version: '3.4'

services:
  personal-accounts-php:
    image: personal-accounts-php
    container_name: personal-accounts-php
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 403:80
    networks:
      - mariadb

networks:
  mariadb:
    external: true
